# Generated by Django 4.2 on 2024-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='1', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
